name: instaappusthb
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  sizer: ^2.0.15              # Required for responsive design system
  flutter_svg: ^2.0.9         # Required for SVG icon support
  google_fonts: ^6.1.0        # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2  # Required for local data storage
  web: ^1.1.1

  # Feature dependencies - safe to modify
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  flutter_slidable: ^4.0.1
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  permission_handler: ^11.1.0
  qr_flutter: ^4.1.0
  record: ^6.0.0
  file_picker: ^8.1.7
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  video_player: ^2.10.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  http: ^1.5.0
  supabase_flutter: ^2.10.0
  firebase_storage: ^13.0.1
  rxdart: ^0.28.0
  share_plus: ^11.1.0
  image_cropper: ^9.1.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/